title: "LuddmiApps"
email: ludmiapps@gmail.com
timezone: UTC
baseurl: ""
permalink: "/:title/"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
author: LudmiApps
paginate: 30
disqus: 'luddmiapps'
locale: en_us
lang: en_us
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
ganalytics:

# Authors
authors:
  sil:
    name: Silvina
    display_name: Silvina
    avatar: 'assets/images/sil.png'
    email: ludmiapps@gmail.com
    web: https://silvinaroldan.github.io
    twitter: https://twitter.com/silvinaroldan
    description: "I'm an iOS and visionOS developer with a passion for creating innovative applications. Alongside my technical skills, I'm also an astrologer, which allows me to bring a unique perspective to my life. I have a deep love for Apple products and their ecosystem, constantly exploring new ways to leverage technology to enhance user experiences"
  
# Social
social:
  instagram: https://www.instagram.com/ludmiapps/
  twitter: https://twitter.com/silvinaroldan

# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives
